### ISSUE TITLE
Did you mean that we do not need learn C++ any more? :-P

### ISSUE THREAD

**Issue by tan-wei** [utilForever/cpp-developer-roadmap#3]
Just a joking. So what about the update?

**Comment by PandoriaRein** [comment]
> 
> 
> Just a joking. So what about the update?

Hello from 2020. Looks like we still dont need learn C++

**Comment by tan-wei** [comment]
> 
> 
> > Just a joking. So what about the update?
> 
> Hello from 2020. Looks like we still dont need learn C++

Ha, I would say congratulations to you. Actually, C++ is not the only choice in many areas.

**Comment by PandoriaRein** [comment]
> 
> Ha, I would say congratulations to you. Actually, C++ is not the only choice in many areas.
>
Yep, but we can use C++ in many areas)

**Comment by utilForever** [comment]
Sorry for the late reply. Currently, I'm working on [RosettaStone](https://github.com/utilForever/RosettaStone) and [CubbyFlow](https://github.com/utilForever/CubbyFlow) project. Also, I'm writing C++20 based summary book with a co-worker. I'll reconstruct the table of contents and reflect them in this repository, so please wait. Thank you very much.

**Comment by tan-wei** [comment]
@utilForever: Great!

**Comment by tsar0720** [comment]
In 2021, we were still waiting cpp-developer-roadmap 2020 :D

**Comment by tan-wei** [comment]
> In 2021, we were still waiting cpp-developer-roadmap 2020 :D

:LOL
