### ISSUE TITLE
Project abandoned? 

### ISSUE THREAD

**Issue by ashkln** [utilForever/cpp-developer-roadmap#6]
I see that its been awhile since the last commit on this repo. Just curious if it's still maintained or this has been abandoned.

If you need help, please let us know (probably in the form of a milestone). Folks from the community would surely like to help.

**Comment by utilForever** [comment]
Hello, this repo is not dead. Anyway, I'm sorry.
I'm translating the book "C++ Crash Course" to Korean.
I'm working on a road map with a lot of help.
From now on, I will update it on a weekly basis. Once again, I apologize for the delay.

**Comment by ashkln** [comment]
Thanks a lot for the reply! And thank you for keeping us updated.
